import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "../styles/fonts.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
